# This file was generated by Nuitka

# Stubs included by default
from __future__ import annotations
from typing import Any
from typing_extensions import Self

class StockPurchase:
    def __init__(self: Self, stock_symbol: str, cost_per_share: float) -> None: ...
    def __eq__(self: Self, other: Any) -> bool: ...
    def __str__(self: Self) -> str: ...
    def __lt__(self: Self, other: Any) -> bool: ...


__name__ = ...



# No other modules used internally, no implicit dependencies.
